data_source retail:
  type: bigquery
  connection:
    account_info_json_path: /usr/local/airflow/include/gcp/service_account.json
    auth_scopes:
      - https://www.googleapis.com/auth/bigquery
      - https://www.googleapis.com/auth/cloud-platform
      - https://www.googleapis.com/auth/drive
    project_id: "retail-stats"
    dataset: retail
soda_cloud:
  host: beta.soda.io
  api_key_id: 5201084f-e464-492b-b543-c22e245ba84a
  api_key_secret: Fmt7ErquGzfwoKJhwcjo7MPNqthtzcXDewGHj4gH0IUEKCKZsiGMTg
